//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Communication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Communication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_say_other#.
        /// </summary>
        internal static string MSG_CHANEL_SAY_OTHER {
            get {
                return ResourceManager.GetString("MSG_CHANEL_SAY_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_emote_other#.
        /// </summary>
        internal static string MSG_CHANNEL_EMOTE_OTHER {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_EMOTE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_emote_self#.
        /// </summary>
        internal static string MSG_CHANNEL_EMOTE_SELF {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_EMOTE_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_noinput#.
        /// </summary>
        internal static string MSG_CHANNEL_NOINPUT {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_NOINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_nouser#.
        /// </summary>
        internal static string MSG_CHANNEL_NOUSER {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_NOUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #channel_say_self#.
        /// </summary>
        internal static string MSG_CHANNEL_SAY_SELF {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_SAY_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelManager initialized..
        /// </summary>
        internal static string MSG_MGR_INITIALIZE {
            get {
                return ResourceManager.GetString("MSG_MGR_INITIALIZE", resourceCulture);
            }
        }
    }
}
