//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BooleanSet not found.
        /// </summary>
        internal static string ERR_BOOLEAN_SET_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_BOOLEAN_SET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition file {0} was not a ZoneDef file..
        /// </summary>
        internal static string ERR_DEF_WAS_NOT_ZONE_DEF {
            get {
                return ResourceManager.GetString("ERR_DEF_WAS_NOT_ZONE_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {0} failed to initialize..
        /// </summary>
        internal static string ERR_FAIL_INITIALIZE_MANAGER {
            get {
                return ResourceManager.GetString("ERR_FAIL_INITIALIZE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate object of Type {0} with Id {1}.
        /// </summary>
        internal static string ERR_FAIL_INSTANTIATE_OBJECT {
            get {
                return ResourceManager.GetString("ERR_FAIL_INSTANTIATE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity [Type={0}, ID={1}, DefID={2}] could not be instantiated..
        /// </summary>
        internal static string ERR_FAILURE_INSTANTIATE {
            get {
                return ResourceManager.GetString("ERR_FAILURE_INSTANTIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to load data in {0}.
        /// </summary>
        internal static string ERR_LOAD_FAILURE {
            get {
                return ResourceManager.GetString("ERR_LOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Zone list is missing..
        /// </summary>
        internal static string ERR_NO_STARTUP_ZONES {
            get {
                return ResourceManager.GetString("ERR_NO_STARTUP_ZONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type {0} cannot be added to Entity Repository.
        /// </summary>
        internal static string ERR_REPOSITORY_INVALID_TYPE {
            get {
                return ResourceManager.GetString("ERR_REPOSITORY_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition for Zone {0} not found..
        /// </summary>
        internal static string ERR_ZONE_DEF_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ZONE_DEF_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity saved from recycling. {0} {1}.
        /// </summary>
        internal static string MSG_ENTITY_SAVED {
            get {
                return ResourceManager.GetString("MSG_ENTITY_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {0} initialized..
        /// </summary>
        internal static string MSG_INITIALIZE_MANAGER {
            get {
                return ResourceManager.GetString("MSG_INITIALIZE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task to save Entity {0} cancelled..
        /// </summary>
        internal static string MSG_TASK_CANCELLED {
            get {
                return ResourceManager.GetString("MSG_TASK_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zones instantiated at startup..
        /// </summary>
        internal static string MSG_ZONE_STARTUP {
            get {
                return ResourceManager.GetString("MSG_ZONE_STARTUP", resourceCulture);
            }
        }
    }
}
