//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Library.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Library.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection contains no values.
        /// </summary>
        internal static string ERR_EMPTY_COLLECTION {
            get {
                return ResourceManager.GetString("ERR_EMPTY_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dequeue event from EventQueue.
        /// </summary>
        internal static string ERR_EVENT_DEQUEUE_FAILURE {
            get {
                return ResourceManager.GetString("ERR_EVENT_DEQUEUE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Event of type {0}..
        /// </summary>
        internal static string ERR_EVENT_INSTANTIATE_FAILURE {
            get {
                return ResourceManager.GetString("ERR_EVENT_INSTANTIATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency value of {0} is not allowed..
        /// </summary>
        internal static string ERR_INVALID_FREQUENCY {
            get {
                return ResourceManager.GetString("ERR_INVALID_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hour (must be between 0 and 24).
        /// </summary>
        internal static string ERR_INVALID_HOUR {
            get {
                return ResourceManager.GetString("ERR_INVALID_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not and does not derive from type {0}..
        /// </summary>
        internal static string ERR_INVALID_TYPE {
            get {
                return ResourceManager.GetString("ERR_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        internal static string ERR_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain a value member = {1}.
        /// </summary>
        internal static string ERR_NO_VALUE {
            get {
                return ResourceManager.GetString("ERR_NO_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback function was null.
        /// </summary>
        internal static string ERR_NULL_CALLBACK {
            get {
                return ResourceManager.GetString("ERR_NULL_CALLBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null.
        /// </summary>
        internal static string ERR_NULL_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_NULL_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}(BoolAtom).
        /// </summary>
        internal static string LOG_BOOL_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_BOOL_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (DictionaryAtom).
        /// </summary>
        internal static string LOG_DICT_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_DICT_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string LOG_DICT_ATOM_KEY {
            get {
                return ResourceManager.GetString("LOG_DICT_ATOM_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} (null).
        /// </summary>
        internal static string LOG_DICT_ATOM_NULL_KEY {
            get {
                return ResourceManager.GetString("LOG_DICT_ATOM_NULL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}(IntAtom).
        /// </summary>
        internal static string LOG_INT_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_INT_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(ListAtom).
        /// </summary>
        internal static string LOG_LIST_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_LIST_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}(ObjectAtom).
        /// </summary>
        internal static string LOG_OBJECT_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_OBJECT_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}(RealAtom).
        /// </summary>
        internal static string LOG_REAL_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_REAL_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}(StringAtom).
        /// </summary>
        internal static string LOG_STRING_ATOM_FORMAT {
            get {
                return ResourceManager.GetString("LOG_STRING_ATOM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the afternoon.
        /// </summary>
        internal static string MSG_AFTERNOON {
            get {
                return ResourceManager.GetString("MSG_AFTERNOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string MSG_AND {
            get {
                return ResourceManager.GetString("MSG_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string MSG_EIGHT {
            get {
                return ResourceManager.GetString("MSG_EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighteen.
        /// </summary>
        internal static string MSG_EIGHTEEN {
            get {
                return ResourceManager.GetString("MSG_EIGHTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty.
        /// </summary>
        internal static string MSG_EIGHTY {
            get {
                return ResourceManager.GetString("MSG_EIGHTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleven.
        /// </summary>
        internal static string MSG_ELEVEN {
            get {
                return ResourceManager.GetString("MSG_ELEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the evening.
        /// </summary>
        internal static string MSG_EVENING {
            get {
                return ResourceManager.GetString("MSG_EVENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred in {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_LOCATION {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteen.
        /// </summary>
        internal static string MSG_FIFTEEN {
            get {
                return ResourceManager.GetString("MSG_FIFTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty.
        /// </summary>
        internal static string MSG_FIFTY {
            get {
                return ResourceManager.GetString("MSG_FIFTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        internal static string MSG_FIVE {
            get {
                return ResourceManager.GetString("MSG_FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forty.
        /// </summary>
        internal static string MSG_FORTY {
            get {
                return ResourceManager.GetString("MSG_FORTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        internal static string MSG_FOUR {
            get {
                return ResourceManager.GetString("MSG_FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        internal static string MSG_FOURTEEN {
            get {
                return ResourceManager.GetString("MSG_FOURTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hundred.
        /// </summary>
        internal static string MSG_HUNDRED {
            get {
                return ResourceManager.GetString("MSG_HUNDRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {0} initialized..
        /// </summary>
        internal static string MSG_INITIALIZE_MANAGER {
            get {
                return ResourceManager.GetString("MSG_INITIALIZE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        internal static string MSG_MILLION {
            get {
                return ResourceManager.GetString("MSG_MILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        internal static string MSG_MINUS {
            get {
                return ResourceManager.GetString("MSG_MINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the morning.
        /// </summary>
        internal static string MSG_MORNING {
            get {
                return ResourceManager.GetString("MSG_MORNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at night.
        /// </summary>
        internal static string MSG_NIGHT {
            get {
                return ResourceManager.GetString("MSG_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        internal static string MSG_NINE {
            get {
                return ResourceManager.GetString("MSG_NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineteen.
        /// </summary>
        internal static string MSG_NINETEEN {
            get {
                return ResourceManager.GetString("MSG_NINETEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety.
        /// </summary>
        internal static string MSG_NINETY {
            get {
                return ResourceManager.GetString("MSG_NINETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        internal static string MSG_ONE {
            get {
                return ResourceManager.GetString("MSG_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        internal static string MSG_SEVEN {
            get {
                return ResourceManager.GetString("MSG_SEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventeen.
        /// </summary>
        internal static string MSG_SEVENTEEN {
            get {
                return ResourceManager.GetString("MSG_SEVENTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy.
        /// </summary>
        internal static string MSG_SEVENTY {
            get {
                return ResourceManager.GetString("MSG_SEVENTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        internal static string MSG_SIX {
            get {
                return ResourceManager.GetString("MSG_SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteen.
        /// </summary>
        internal static string MSG_SIXTEEN {
            get {
                return ResourceManager.GetString("MSG_SIXTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty.
        /// </summary>
        internal static string MSG_SIXTY {
            get {
                return ResourceManager.GetString("MSG_SIXTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        internal static string MSG_TEN {
            get {
                return ResourceManager.GetString("MSG_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteen.
        /// </summary>
        internal static string MSG_THIRTEEN {
            get {
                return ResourceManager.GetString("MSG_THIRTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty.
        /// </summary>
        internal static string MSG_THIRTY {
            get {
                return ResourceManager.GetString("MSG_THIRTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand.
        /// </summary>
        internal static string MSG_THOUSAND {
            get {
                return ResourceManager.GetString("MSG_THOUSAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        internal static string MSG_THREE {
            get {
                return ResourceManager.GetString("MSG_THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        internal static string MSG_TWELVE {
            get {
                return ResourceManager.GetString("MSG_TWELVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty.
        /// </summary>
        internal static string MSG_TWENTY {
            get {
                return ResourceManager.GetString("MSG_TWENTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        internal static string MSG_TWO {
            get {
                return ResourceManager.GetString("MSG_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        internal static string MSG_ZERO {
            get {
                return ResourceManager.GetString("MSG_ZERO", resourceCulture);
            }
        }
    }
}
