//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Server.Properties.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner[{0}, {1}] is not an IRegularMob..
        /// </summary>
        internal static string ERR_AI_OWNER_NOT_MOBILE {
            get {
                return ResourceManager.GetString("ERR_AI_OWNER_NOT_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiState[{0}] found no Owner.
        /// </summary>
        internal static string ERR_AISTATE_NO_OWNER {
            get {
                return ResourceManager.GetString("ERR_AISTATE_NO_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AppSetting &apos;{0}&apos; found in app.config..
        /// </summary>
        internal static string ERR_APP_SETTING_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_APP_SETTING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biota[{0}, {1}] is not attackable.
        /// </summary>
        internal static string ERR_BIOTA_NOT_ATTACKABLE {
            get {
                return ResourceManager.GetString("ERR_BIOTA_NOT_ATTACKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel[{0}, {1}] found a null owner[{2}].
        /// </summary>
        internal static string ERR_CHANNEL_NO_OWNER {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_NO_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel[{0}, {1}], {2} members, {3} message length.
        /// </summary>
        internal static string ERR_CHANNEL_TEXT_NOMEMBERS_OR_NOTEXT {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_TEXT_NOMEMBERS_OR_NOTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate &apos;{0}&apos; command.
        /// </summary>
        internal static string ERR_COMMAND_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_COMMAND_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate Effect[{0}].
        /// </summary>
        internal static string ERR_EFFECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_EFFECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory[{0}] could not be found.
        /// </summary>
        internal static string ERR_FACTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_FACTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create AiStateTemplate[{0}, {1}].
        /// </summary>
        internal static string ERR_FAIL_CREATE_AISTATE {
            get {
                return ResourceManager.GetString("ERR_FAIL_CREATE_AISTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Object {0}.
        /// </summary>
        internal static string ERR_FAIL_CREATE_OBJECT {
            get {
                return ResourceManager.GetString("ERR_FAIL_CREATE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {0} failed to initialize..
        /// </summary>
        internal static string ERR_FAIL_INITIALIZE_MANAGER {
            get {
                return ResourceManager.GetString("ERR_FAIL_INITIALIZE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate {0} with Id {1} and Parent {2}.
        /// </summary>
        internal static string ERR_FAIL_INSTANTIATE_INSTANCE {
            get {
                return ResourceManager.GetString("ERR_FAIL_INSTANTIATE_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate {0} with Id {1} and Name {2}.
        /// </summary>
        internal static string ERR_FAIL_INSTANTIATE_TEMPLATE {
            get {
                return ResourceManager.GetString("ERR_FAIL_INSTANTIATE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaMachine failed to initialize.
        /// </summary>
        internal static string ERR_FAIL_LUA_INITIALIZE {
            get {
                return ResourceManager.GetString("ERR_FAIL_LUA_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag {0} not found..
        /// </summary>
        internal static string ERR_FLAG_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_FLAG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Insufficient Arguments.
        /// </summary>
        internal static string ERR_INSUF_ARGUMENTS {
            get {
                return ResourceManager.GetString("ERR_INSUF_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object type.
        /// </summary>
        internal static string ERR_INVALID_OBJECT_TYPE {
            get {
                return ResourceManager.GetString("ERR_INVALID_OBJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob[{0}, {1}] has a null Location..
        /// </summary>
        internal static string ERR_MOBILE_NO_LOCATION {
            get {
                return ResourceManager.GetString("ERR_MOBILE_NO_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data for Element {0} was invalid.
        /// </summary>
        internal static string ERR_NULL_EXTRA_DATA {
            get {
                return ResourceManager.GetString("ERR_NULL_EXTRA_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null.
        /// </summary>
        internal static string ERR_NULL_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_NULL_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate Reagant[{0}].
        /// </summary>
        internal static string ERR_REAGANT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_REAGANT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User[{0}] already exists in the UserRepository..
        /// </summary>
        internal static string ERR_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERR_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcpUser[{0}] was not found..
        /// </summary>
        internal static string ERR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
