//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Server.Properties.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_create_inv#.
        /// </summary>
        internal static string MSG_ADMIN_CREATE_INV {
            get {
                return ResourceManager.GetString("MSG_ADMIN_CREATE_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_create_other#.
        /// </summary>
        internal static string MSG_ADMIN_CREATE_OTHER {
            get {
                return ResourceManager.GetString("MSG_ADMIN_CREATE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_create_self#.
        /// </summary>
        internal static string MSG_ADMIN_CREATE_SELF {
            get {
                return ResourceManager.GetString("MSG_ADMIN_CREATE_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_detail_off#.
        /// </summary>
        internal static string MSG_ADMIN_DETAIL_OFF {
            get {
                return ResourceManager.GetString("MSG_ADMIN_DETAIL_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_detail_on#.
        /// </summary>
        internal static string MSG_ADMIN_DETAIL_ON {
            get {
                return ResourceManager.GetString("MSG_ADMIN_DETAIL_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} #{1}] {2}.
        /// </summary>
        internal static string MSG_ADMIN_MONITOR_SPAWN {
            get {
                return ResourceManager.GetString("MSG_ADMIN_MONITOR_SPAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_not_entity#.
        /// </summary>
        internal static string MSG_ADMIN_NOT_ENTITY {
            get {
                return ResourceManager.GetString("MSG_ADMIN_NOT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_not_mob#.
        /// </summary>
        internal static string MSG_ADMIN_NOT_MOB {
            get {
                return ResourceManager.GetString("MSG_ADMIN_NOT_MOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_save#.
        /// </summary>
        internal static string MSG_ADMIN_SAVE {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_save_not_found#.
        /// </summary>
        internal static string MSG_ADMIN_SAVE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SAVE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_save_other#.
        /// </summary>
        internal static string MSG_ADMIN_SAVE_OTHER {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SAVE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_save_self#.
        /// </summary>
        internal static string MSG_ADMIN_SAVE_SELF {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SAVE_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_save_target#.
        /// </summary>
        internal static string MSG_ADMIN_SAVE_TARGET {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SAVE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_spawn_self#.
        /// </summary>
        internal static string MSG_ADMIN_SPAWN_SELF {
            get {
                return ResourceManager.GetString("MSG_ADMIN_SPAWN_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #admin_where#.
        /// </summary>
        internal static string MSG_ADMIN_WHERE {
            get {
                return ResourceManager.GetString("MSG_ADMIN_WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already at destination.
        /// </summary>
        internal static string MSG_AI_ALREADY_AT_DESTINATION {
            get {
                return ResourceManager.GetString("MSG_AI_ALREADY_AT_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not moving this tick.
        /// </summary>
        internal static string MSG_AI_CHOSE_NOT_TO_MOVE {
            get {
                return ResourceManager.GetString("MSG_AI_CHOSE_NOT_TO_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m in combat, can&apos;t wander!  How did WanderState get to the top?.
        /// </summary>
        internal static string MSG_AI_COMBAT_CANNOT_WANDER {
            get {
                return ResourceManager.GetString("MSG_AI_COMBAT_CANNOT_WANDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move location.
        /// </summary>
        internal static string MSG_AI_INVALID_DESTINATION {
            get {
                return ResourceManager.GetString("MSG_AI_INVALID_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m moving to destination {0}.
        /// </summary>
        internal static string MSG_AI_MOVING_TO {
            get {
                return ResourceManager.GetString("MSG_AI_MOVING_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob[{0}, {1}] =&gt; NeedState =&gt; IsDead..
        /// </summary>
        internal static string MSG_AI_NEEDSTATE_ISDEAD {
            get {
                return ResourceManager.GetString("MSG_AI_NEEDSTATE_ISDEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob[{0}, {1}] =&gt; NeedState =&gt; DoNothing..
        /// </summary>
        internal static string MSG_AI_NEEDSTATE_NOTHING {
            get {
                return ResourceManager.GetString("MSG_AI_NEEDSTATE_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob[{0}, {1}] =&gt; NeedState =&gt; State[{2}, {3}]..
        /// </summary>
        internal static string MSG_AI_NEEDSTATE_STATE {
            get {
                return ResourceManager.GetString("MSG_AI_NEEDSTATE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No portal from my current location to my destination.
        /// </summary>
        internal static string MSG_AI_NO_PORTAL_TO_DESTINATION {
            get {
                return ResourceManager.GetString("MSG_AI_NO_PORTAL_TO_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a stationary mob!  Why do I have a Wander state?.
        /// </summary>
        internal static string MSG_AI_STATIONARY_CANNOT_WANDER {
            get {
                return ResourceManager.GetString("MSG_AI_STATIONARY_CANNOT_WANDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_dead#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_DEAD {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_DEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_dir#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_DIR {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_fighting#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_FIGHTING {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_FIGHTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_nodir#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_NODIR {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_NODIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_noexits#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_NOEXITS {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_NOEXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_notallow#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_NOTALLOW {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_NOTALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_position#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_POSITION {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_insufstamina#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_STAMINA {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_STAMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cannot_move_terrain#.
        /// </summary>
        internal static string MSG_CANNOT_MOVE_TERRAIN {
            get {
                return ResourceManager.GetString("MSG_CANNOT_MOVE_TERRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction[{0}] added to Channel[{1}, {2}].
        /// </summary>
        internal static string MSG_CHANNEL_ADD_RESTRICTION {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_ADD_RESTRICTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has passed ownership of the channel to {1}..
        /// </summary>
        internal static string MSG_CHANNEL_CHANGE_OWNER {
            get {
                return ResourceManager.GetString("MSG_CHANNEL_CHANGE_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copper.
        /// </summary>
        internal static string MSG_COPPER_LONG {
            get {
                return ResourceManager.GetString("MSG_COPPER_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}c.
        /// </summary>
        internal static string MSG_COPPER_SHORT {
            get {
                return ResourceManager.GetString("MSG_COPPER_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the {0} day of {1} in the year {2}..
        /// </summary>
        internal static string MSG_DATE_NOT_SHROUDING {
            get {
                return ResourceManager.GetString("MSG_DATE_NOT_SHROUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the {0} in the year {1}..
        /// </summary>
        internal static string MSG_DATE_SHROUDING {
            get {
                return ResourceManager.GetString("MSG_DATE_SHROUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect[{0}] added to Ability[{1}, {2}].
        /// </summary>
        internal static string MSG_EFFECT_ADDED_TO_ABILITY {
            get {
                return ResourceManager.GetString("MSG_EFFECT_ADDED_TO_ABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #error#.
        /// </summary>
        internal static string MSG_ERR {
            get {
                return ResourceManager.GetString("MSG_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Startup :: Segment Length is {0} milliseconds..
        /// </summary>
        internal static string MSG_GAME_START {
            get {
                return ResourceManager.GetString("MSG_GAME_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Game Loop at {0}.
        /// </summary>
        internal static string MSG_GAME_STOP {
            get {
                return ResourceManager.GetString("MSG_GAME_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gold.
        /// </summary>
        internal static string MSG_GOLD_LONG {
            get {
                return ResourceManager.GetString("MSG_GOLD_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}g.
        /// </summary>
        internal static string MSG_GOLD_SHORT {
            get {
                return ResourceManager.GetString("MSG_GOLD_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #help_entry#.
        /// </summary>
        internal static string MSG_HELP_ENTRY {
            get {
                return ResourceManager.GetString("MSG_HELP_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #help_no_default#.
        /// </summary>
        internal static string MSG_HELP_NO_DEFAULT {
            get {
                return ResourceManager.GetString("MSG_HELP_NO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #help_no_entry#.
        /// </summary>
        internal static string MSG_HELP_NO_ENTRY {
            get {
                return ResourceManager.GetString("MSG_HELP_NO_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {0} initialized..
        /// </summary>
        internal static string MSG_INITIALIZE_MANAGER {
            get {
                return ResourceManager.GetString("MSG_INITIALIZE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #invalid_menu#.
        /// </summary>
        internal static string MSG_INVALID_MENU {
            get {
                return ResourceManager.GetString("MSG_INVALID_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Instance[{0}] added to AIBucket[{1}].
        /// </summary>
        internal static string MSG_MOBILE_ADDED_TO_BUCKET {
            get {
                return ResourceManager.GetString("MSG_MOBILE_ADDED_TO_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Instance[{0}] removed from AIBucket[{1}].
        /// </summary>
        internal static string MSG_MOBILE_REMOVED_FROM_BUCKET {
            get {
                return ResourceManager.GetString("MSG_MOBILE_REMOVED_FROM_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #no_item#.
        /// </summary>
        internal static string MSG_NO_ITEM {
            get {
                return ResourceManager.GetString("MSG_NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #no_mob#.
        /// </summary>
        internal static string MSG_NO_MOB {
            get {
                return ResourceManager.GetString("MSG_NO_MOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #no_object#.
        /// </summary>
        internal static string MSG_NO_OBJECT {
            get {
                return ResourceManager.GetString("MSG_NO_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #not_authorized#.
        /// </summary>
        internal static string MSG_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("MSG_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #not_functional#.
        /// </summary>
        internal static string MSG_NOT_FUNCTIONAL {
            get {
                return ResourceManager.GetString("MSG_NOT_FUNCTIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #not_in_space#.
        /// </summary>
        internal static string MSG_NOT_IN_SPACE {
            get {
                return ResourceManager.GetString("MSG_NOT_IN_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #not_understand#.
        /// </summary>
        internal static string MSG_NOT_UNDERSTAND {
            get {
                return ResourceManager.GetString("MSG_NOT_UNDERSTAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nothing_here#.
        /// </summary>
        internal static string MSG_NOTHING_HERE {
            get {
                return ResourceManager.GetString("MSG_NOTHING_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} platinum.
        /// </summary>
        internal static string MSG_PLATINUM_LONG {
            get {
                return ResourceManager.GetString("MSG_PLATINUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}p.
        /// </summary>
        internal static string MSG_PLATINUM_SHORT {
            get {
                return ResourceManager.GetString("MSG_PLATINUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for playing!  Good-bye..
        /// </summary>
        internal static string MSG_QUIT {
            get {
                return ResourceManager.GetString("MSG_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagant[{0}] added to Ability[{1}, {2}].
        /// </summary>
        internal static string MSG_REAGANT_ADDED_TO_ABILITY {
            get {
                return ResourceManager.GetString("MSG_REAGANT_ADDED_TO_ABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character data saved successfully..
        /// </summary>
        internal static string MSG_SAVE_SUCCESSFUL {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} silver.
        /// </summary>
        internal static string MSG_SILVER_LONG {
            get {
                return ResourceManager.GetString("MSG_SILVER_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        internal static string MSG_SILVER_SHORT {
            get {
                return ResourceManager.GetString("MSG_SILVER_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initialized..
        /// </summary>
        internal static string MSG_SINGLETON_INITIALIZED {
            get {
                return ResourceManager.GetString("MSG_SINGLETON_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #tel_cannot_enter#.
        /// </summary>
        internal static string MSG_TEL_CANNOT_ENTER {
            get {
                return ResourceManager.GetString("MSG_TEL_CANNOT_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #tel_invalid_dest.
        /// </summary>
        internal static string MSG_TEL_INVALID_DEST {
            get {
                return ResourceManager.GetString("MSG_TEL_INVALID_DEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time is about {0} o&apos;clock {1}..
        /// </summary>
        internal static string MSG_TIME {
            get {
                return ResourceManager.GetString("MSG_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User[{0}] added to UserRepository..
        /// </summary>
        internal static string MSG_USER_ADDED {
            get {
                return ResourceManager.GetString("MSG_USER_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #username_long#.
        /// </summary>
        internal static string MSG_USERNAME_LONG {
            get {
                return ResourceManager.GetString("MSG_USERNAME_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #username_short#.
        /// </summary>
        internal static string MSG_USERNAME_SHORT {
            get {
                return ResourceManager.GetString("MSG_USERNAME_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #where_no_char#.
        /// </summary>
        internal static string MSG_WHERE_NO_CHAR {
            get {
                return ResourceManager.GetString("MSG_WHERE_NO_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #where_not_player#.
        /// </summary>
        internal static string MSG_WHERE_NOT_PLAYER {
            get {
                return ResourceManager.GetString("MSG_WHERE_NOT_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone[{0}, {1}] processing {2} Mobs..
        /// </summary>
        internal static string MSG_ZONE_AI_PROCESSING {
            get {
                return ResourceManager.GetString("MSG_ZONE_AI_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zones instantiated at startup..
        /// </summary>
        internal static string MSG_ZONE_STARTUP {
            get {
                return ResourceManager.GetString("MSG_ZONE_STARTUP", resourceCulture);
            }
        }
    }
}
