//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Library.Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Library.Lua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} (exported as {1}) argument number mismatch. Declared {2} but requires {3}..
        /// </summary>
        internal static string ERR_FUNC_ARG_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_FUNC_ARG_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} not found in Lua Script {1}.
        /// </summary>
        internal static string ERR_FUNC_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_FUNC_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file &apos;{0}&apos; was invalid.
        /// </summary>
        internal static string ERR_INVALID_FILE {
            get {
                return ResourceManager.GetString("ERR_INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaTable {0} could not be found..
        /// </summary>
        internal static string ERR_NO_LUATABLE {
            get {
                return ResourceManager.GetString("ERR_NO_LUATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaVM was null.
        /// </summary>
        internal static string ERR_NULL_LUAVM {
            get {
                return ResourceManager.GetString("ERR_NULL_LUAVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null.
        /// </summary>
        internal static string ERR_NULL_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_NULL_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the Lua Virtual Machine.
        /// </summary>
        internal static string ERR_UNABLE_INITIALIZE {
            get {
                return ResourceManager.GetString("ERR_UNABLE_INITIALIZE", resourceCulture);
            }
        }
    }
}
