//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realm.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MxpResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MxpResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realm.Server.Properties.MxpResources", typeof(MxpResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C.
        /// </summary>
        internal static string MXP_TAG_COLOR_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_COLOR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C {0}.
        /// </summary>
        internal static string MXP_TAG_COLOR_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_COLOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Effect.
        /// </summary>
        internal static string MXP_TAG_EFFECT_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_EFFECT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        internal static string MXP_TAG_EFFECT_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_EFFECT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GrndItem.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GrndItem_DrinkCnt.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_DRINKCNT_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_DRINKCNT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrndItem_DrinkCnt &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_DRINKCNT_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_DRINKCNT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrndItem &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GrndItem_ResNode.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_RESNODE_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_RESNODE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrndItem_ResNode &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_GRNDITEM_RESNODE_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_GRNDITEM_RESNODE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Guard.
        /// </summary>
        internal static string MXP_TAG_GUARD_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_GUARD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_GUARD_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_GUARD_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /HelpEntry.
        /// </summary>
        internal static string MXP_TAG_HELPENTRY_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_HELPENTRY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpEntry &apos;{0}&apos;.
        /// </summary>
        internal static string MXP_TAG_HELPENTRY_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_HELPENTRY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Id.
        /// </summary>
        internal static string MXP_TAG_ID_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_ID_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string MXP_TAG_ID_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_ID_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item.
        /// </summary>
        internal static string MXP_TAG_ITEM_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_ITEM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string MXP_TAG_ITEM_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_ITEM_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mob.
        /// </summary>
        internal static string MXP_TAG_MOBILE_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_MOBILE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob.
        /// </summary>
        internal static string MXP_TAG_MOBILE_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_MOBILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Portal.
        /// </summary>
        internal static string MXP_TAG_PORTAL_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_PORTAL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_PORTAL_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_PORTAL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RDesc.
        /// </summary>
        internal static string MXP_TAG_RDESC_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_RDESC_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDesc.
        /// </summary>
        internal static string MXP_TAG_RDESC_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_RDESC_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RName.
        /// </summary>
        internal static string MXP_TAG_RNAME_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_RNAME_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RName.
        /// </summary>
        internal static string MXP_TAG_RNAME_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_RNAME_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RPortals.
        /// </summary>
        internal static string MXP_TAG_RPORTALS_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_RPORTALS_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPortals.
        /// </summary>
        internal static string MXP_TAG_RPORTALS_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_RPORTALS_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Shopkeep.
        /// </summary>
        internal static string MXP_TAG_SHOPKEEP_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_SHOPKEEP_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopkeep &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_SHOPKEEP_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_SHOPKEEP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Trainer.
        /// </summary>
        internal static string MXP_TAG_TRAINER_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_TRAINER_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_TRAINER_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_TRAINER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /WizEntity.
        /// </summary>
        internal static string MXP_TAG_WIZENTITY_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZENTITY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizEntity &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_WIZENTITY_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZENTITY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /WizItem.
        /// </summary>
        internal static string MXP_TAG_WIZITEM_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZITEM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizItem &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_WIZITEM_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZITEM_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /WizMob.
        /// </summary>
        internal static string MXP_TAG_WIZMOBILE_CLOSE {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZMOBILE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizMob &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        internal static string MXP_TAG_WIZMOBILE_OPEN {
            get {
                return ResourceManager.GetString("MXP_TAG_WIZMOBILE_OPEN", resourceCulture);
            }
        }
    }
}
